"use client";
import { useState } from "react";
import { SIGNAL_REGISTRY, SERVICE_SCOPES } from "@/lib/enrichment-signals";
import { LEAD_SIGNAL_RECIPES, predicateOperators, validateFilterDefinition, type FilterDefinition, type FilterExpression, type SignalPredicate } from "@/lib/lead-filter-definition";

const initialPredicate = (): SignalPredicate => ({ type: "predicate", signal: "website.active", op: "eq", value: true });
function selectedSignal(id: string): SignalPredicate {
    return predicateOperators(id).includes("unknown") ? { type: "predicate", signal: id, op: "unknown" } : { type: "predicate", signal: id, op: "eq", value: SIGNAL_REGISTRY[id].values?.[0] || "" };
}
const defaultDefinition: FilterDefinition = { version: 2, expression: { type: "all", children: [{ type: "predicate", signal: "legacy.isExistingClient", op: "eq", value: false }, initialPredicate()] } };
const labels: Record<string,string> = { eq: "equals", in: "any of", not_in: "none of (known values)", gte: "at least", lte: "at most", between: "between", recent: "within days", before: "before UTC date", after: "after UTC date", unknown: "unable to verify", fresh: "fresh", stale: "stale", verification: "verification state", outcome: "latest collection outcome", source_domain: "evidence domain" };

function Condition({ node, onChange, onRemove, scopedKind }: { node: FilterExpression; onChange: (node: FilterExpression) => void; onRemove?: () => void; scopedKind?: string }) {
    const [search, setSearch] = useState("");
    const selectStyle = { maxWidth: "100%", padding: "6px", borderRadius: 4 };
    if (node.type === "match_all") return <div>Explicitly match every non-archived lead. <button type="button" onClick={() => onChange(initialPredicate())}>Add a condition</button>{onRemove && <button type="button" onClick={onRemove}>Remove</button>}</div>;
    if (node.type === "scope") return <fieldset style={{ margin: "8px 0", padding: 12 }}><legend>Conditions on the same {node.kind}</legend><select aria-label="Entity service" value={node.scope} onChange={e => onChange({ ...node, scope: e.target.value as typeof node.scope })}>{SERVICE_SCOPES.map(scope => <option key={scope}>{scope}</option>)}</select><Condition node={node.expression} scopedKind={node.kind} onChange={expression => onChange({ ...node, expression })} />{onRemove && <button type="button" onClick={onRemove}>Remove scope</button>}</fieldset>;
    if (node.type === "all" || node.type === "any") return <fieldset style={{ margin: "8px 0", padding: 12 }}><legend><select aria-label="Combine conditions" value={node.type} onChange={e => onChange({ ...node, type: e.target.value as "all" | "any" })}><option value="all">ALL conditions</option><option value="any">ANY condition</option></select></legend>
        {node.children.map((child, index) => <Condition key={index} node={child} scopedKind={scopedKind} onChange={replacement => onChange({ ...node, children: node.children.map((existing, i) => i === index ? replacement : existing) })} onRemove={() => onChange({ ...node, children: node.children.filter((_, i) => i !== index) })} />)}
        <button type="button" onClick={() => { const signal = scopedKind ? Object.values(SIGNAL_REGISTRY).find(s => s.kind === scopedKind && !s.legacyField)! : SIGNAL_REGISTRY["website.active"]; onChange({ ...node, children: [...node.children, { type: "predicate", signal: signal.id, op: "unknown" }] }); }}>Add condition</button>{" "}
        <button type="button" onClick={() => onChange({ ...node, children: [...node.children, { type: "any", children: [{ type: "predicate", signal: scopedKind ? Object.values(SIGNAL_REGISTRY).find(s => s.kind === scopedKind && !s.legacyField)!.id : "website.active", op: "unknown" }] }] })}>Add ALL/ANY group</button>{" "}
        {!scopedKind && <select aria-label="Add correlated evidence" value="" onChange={e => { if (e.target.value) onChange({ ...node, children: [...node.children, { type: "scope", kind: e.target.value as "route", scope: ["review", "activity"].includes(e.target.value) ? "business" : "junk_removal", expression: { type: "all", children: [{ type: "predicate", signal: Object.values(SIGNAL_REGISTRY).find(s => s.kind === e.target.value && !s.legacyField)!.id, op: "unknown" }] } }] }); }}><option value="">Add same-entity conditions…</option>{["service", "route", "review", "promise", "activity"].map(kind => <option key={kind}>{kind}</option>)}</select>}
        {onRemove && <button type="button" onClick={onRemove}>Remove group</button>}
    </fieldset>;
    const signal = SIGNAL_REGISTRY[node.signal];
    const matchingSignals = Object.values(SIGNAL_REGISTRY).filter(s => (!scopedKind || s.kind === scopedKind && !s.legacyField) && (s.id === node.signal || `${s.label} ${s.id}`.toLowerCase().includes(search.toLowerCase())));
    const signals = [signal, ...matchingSignals.filter(s => s.id !== node.signal)].slice(0, 40);
    const update = (patch: Partial<SignalPredicate>) => onChange({ ...node, ...patch });
    return <div style={{ padding: "10px 0", borderBottom: "1px solid #8885", display: "flex", gap: 8, flexWrap: "wrap", alignItems: "center" }}>
        <input aria-label="Search signals" placeholder="Search all signals…" value={search} onChange={e => setSearch(e.target.value)} style={{ width: 150 }} />
        <select style={selectStyle} aria-label="Signal" value={node.signal} onChange={e => onChange(selectedSignal(e.target.value))}>{["Evidence", "Legacy / operational"].map(group => <optgroup label={group} key={group}>{signals.filter(s => Boolean(s.legacyField) === (group !== "Evidence")).map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</optgroup>)}</select>
        <select aria-label="Operator" value={node.op} onChange={e => { const op = e.target.value as SignalPredicate["op"]; const next: SignalPredicate = { type: "predicate", signal: node.signal, op, ...(node.scope ? { scope: node.scope } : {}) }; if (op === "recent") next.days = 90; else if (op === "between") { next.min = 1; next.max = 3; } else if (!["unknown", "fresh", "stale"].includes(op)) next.value = op === "verification" ? "confirmed" : op === "outcome" ? "success" : op === "source_domain" ? "example.com" : op === "in" || op === "not_in" ? [signal.values?.[0] || ""] : signal.type === "boolean" ? true : ["number", "count", "date"].includes(signal.type) ? 1 : signal.values?.[0] || ""; onChange(next); }}>{predicateOperators(node.signal).map(op => <option key={op} value={op}>{labels[op]}</option>)}</select>
        {node.op === "between" ? <><input aria-label="Minimum" type="number" value={node.min ?? ""} onChange={e => update({ min: e.target.value === "" ? undefined : Number(e.target.value) })} style={{ width: 90 }} />to<input aria-label="Maximum" type="number" value={node.max ?? ""} onChange={e => update({ max: e.target.value === "" ? undefined : Number(e.target.value) })} style={{ width: 90 }} /></> : node.op === "recent" ? <input aria-label="Days" type="number" min={1} value={node.days ?? 90} onChange={e => update({ days: Number(e.target.value) })} style={{ width: 90 }} /> : ["unknown", "fresh", "stale"].includes(node.op) ? null : node.op === "before" || node.op === "after" ? <input aria-label="UTC boundary date" type="date" value={typeof node.value === "number" && Number.isFinite(node.value) ? new Date(node.value).toISOString().slice(0,10) : ""} onChange={e => update({ value: Date.parse(`${e.target.value}T00:00:00Z`) })} /> : signal.type === "boolean" && node.op === "eq" ? <select aria-label="Value" value={String(node.value)} onChange={e => update({ value: e.target.value === "true" })}><option value="true">Yes</option><option value="false">{signal.legacyField ? "Stored No (legacy limitations apply)" : "No — verified absence"}</option></select> : <input aria-label="Value" placeholder={node.op === "in" || node.op === "not_in" ? "Comma-separated values" : "Value"} value={Array.isArray(node.value) ? node.value.join(",") : String(node.value ?? "")} onChange={e => update({ value: node.op === "in" || node.op === "not_in" ? e.target.value.split(",").map(s => s.trim()) : ["number", "count"].includes(signal.type) && !["verification", "outcome", "source_domain"].includes(node.op) ? Number(e.target.value) : e.target.value })} />}
        {signal.type === "count" && !["unknown", "outcome", "verification", "source_domain"].includes(node.op) && <label>Window <input aria-label="Rolling count days" type="number" min={1} value={node.days ?? 90} onChange={e => update({ days: Number(e.target.value) })} style={{ width: 70 }} /> days</label>}
        {!scopedKind && !signal.legacyField && ["service", "route", "promise"].includes(signal.kind) && <select aria-label="Service" value={node.scope || ""} onChange={e => { const next = { ...node }; if (e.target.value) next.scope = e.target.value as SignalPredicate["scope"]; else delete next.scope; onChange(next); }}><option value="">Any service</option>{SERVICE_SCOPES.map(scope => <option key={scope}>{scope}</option>)}</select>}
        {!signal.legacyField && <><select aria-label="Observation state" value={node.states?.includes("inferred") ? "inferred" : "confirmed"} onChange={e => update({ states: [e.target.value as "confirmed" | "inferred"] })}><option value="confirmed">Confirmed only</option><option value="inferred">Inferred only</option></select>{signal.freshnessDays && <label><input type="checkbox" checked={node.freshness === "any"} onChange={e => update({ freshness: e.target.checked ? "any" : "default" })} /> Include old checks</label>}</>}
        {onRemove && <button type="button" onClick={onRemove} aria-label="Remove condition">Remove</button>}
        <small style={{ flexBasis: "100%", opacity: .75 }}>{matchingSignals.length > 40 ? "Showing 40 choices; search to find any signal. " : ""}{signal.limitation || (signal.freshnessDays ? `Default: confirmed check within ${signal.freshnessDays} days. Unknown observations do not match ordinary negative conditions.` : "Uses stored evidence and the displayed check time.")}</small>
    </div>;
}

export function LeadSignalFilters({ initial, available, onApply, onClear, applyLabel = "Preview these rules" }: { initial?: FilterDefinition; available: boolean; onApply: (definition: FilterDefinition) => void; onClear?: () => void; applyLabel?: string }) {
    const [definition, setDefinition] = useState<FilterDefinition>(initial || defaultDefinition);
    const [error, setError] = useState("");
    return <section aria-label="Evidence filter builder" style={{ padding: 16, border: "1px solid #8885", borderRadius: 8, margin: "16px 0" }}>
        <strong>Evidence and flexible rules</strong>
        <p>Use ALL/ANY groups and same-service, same-route or same-review conditions. Groups can overlap. Preview counts describe group membership eligibility; campaign checks happen separately.</p>
        {!available && <p role="status">Activation is disabled pending schema, database, site coverage and comparative cost verification. You can inspect and compose rules here.</p>}
        <select aria-label="Load example recipe" defaultValue="" onChange={e => { const recipe = LEAD_SIGNAL_RECIPES[Number(e.target.value)]; if (recipe) setDefinition(structuredClone(recipe.definition)); }}><option value="">Start from an acceptance recipe…</option>{LEAD_SIGNAL_RECIPES.map((recipe, index) => <option value={index} key={recipe.name}>{recipe.name}</option>)}</select>
        <Condition node={definition.expression} onChange={expression => setDefinition({ version: 2, expression })} />
        {error && <p role="alert">{error}</p>}
        <button type="button" className="btn btn-primary" disabled={!available} onClick={() => { try { const validated = validateFilterDefinition(definition); setError(""); onApply(validated); } catch (e) { setError(e instanceof Error ? e.message : "Invalid rules"); } }}>{applyLabel}</button>{" "}
        <button type="button" onClick={() => { try { validateFilterDefinition(definition); setError("Rules are valid. Activation remains subject to the server gates."); } catch (e) { setError(e instanceof Error ? e.message : "Invalid rules"); } }}>Check rules</button>{" "}
        <button type="button" onClick={() => setDefinition({ version: 2, expression: { type: "match_all" } })}>Explicit match all</button>{" "}
        {onClear && <button type="button" onClick={onClear}>Return to legacy controls</button>}
    </section>;
}
